# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('blood_group', models.IntegerField(choices=[(1, 'I +'), (2, 'II +'), (3, 'III +'), (4, 'IV + '), (5, 'I -'), (6, 'II -'), (7, 'III -'), (8, 'IV -')], null=True)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('illness', models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], null=True)),
                ('illness1', models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], null=True)),
                ('illness2', models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], null=True)),
            ],
        ),
    ]
