# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorlist',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
