# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_profile_illness'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='illness',
            field=models.IntegerField(choices=[(1, 'Bəli'), (2, 'Xeyr')], null=True),
        ),
    ]
